### PR TITLE
Provide precompiled bundle

### PR DESCRIPTION
**Pull request by buchi**
Steps to convert into a precompiled bundle:

### Create package for installing build tools
```
yarn init
yarn add -D requirejs chokidar-cli
```

### Declare a bundle that is built externally

- Remove Resource Records from Registry
- Remove resources from Bundle Records
- Declare `compile` to `false`
- Declare `jscompilation` and `csscompilation` resources
- Declare `depends` (usually `plone`). Only affects order
- Declare `merge_with` (usually `default`)

Example Bundle:
```xml
    <records prefix="plone.bundles/ftw-slider-resources"
             interface='Products.CMFPlone.interfaces.IBundleRegistry'>
        <value key="enabled">True</value>
        <value key="depends">plone</value>
        <value key="stub_js_modules">jquery</value>
        <value key="compile">False</value>
        <value key="jscompilation">++resource++ftw.slider/slider-compiled.js</value>
        <value key="csscompilation">++resource++ftw.slider/slider-compiled.css</value>
        <value key="last_compilation">2019-12-07 15:25:00</value>
        <value key="merge_with">default</value>
    </records>
```

### Create a `main.js` file that requires all js resources that should be included in the bundle
Example:
```javascript
require(['slick', 'slider'], function (slick, slider) {});
```

### Create a build.js configuration file for building the js bundle
Declare `empty:` marker for dependencies already included in the plone bundle (e.g. jquery)
```javascript
({
    baseUrl: "./ftw/slider/browser/resources",
    paths: {
        jquery: "empty:",
    },
    name: "main",
    out: "./ftw/slider/browser/resources/slider-compiled.js"
})
```

### Create a `main.css` file that imports all css resources
```css
@import url('slick.css');
@import url('slider.css');
```

### Create a buildcss.js configuration file for building the css bundle
```javascript
({
    optimizeCss: "standard",
    cssIn: "./ftw/slider/browser/resources/main.css",
    out: "./ftw/slider/browser/resources/slider-compiled.css"
})
```

### Add build and watch commands to package.json
```json
{
    "scripts": {
        "build": "r.js -o build.js && r.js -o buildcss.js",
        "build-css": "r.js -o buildcss.js",
        "build-js": "r.js -o build.js",
        "watch": "chokidar \"./ftw/slider/browser/resources/(*.js|*.css)\" -i \"**/*-compiled.(js|css)\" -c \"if [[ '{path}' = *.js ]]; then r.js -o build.js; else r.js -o buildcss.js; fi;\""
    }
}
```

### Add `.gitattributes` for compiled bundles

Avoids diffing/merging of compiled bundles and excludes bundles in language statistics.
```
*-compiled.js -diff linguist-vendored
*-compiled.css -diff linguist-vendored
```

### Remarks
- In production the merged bundle needs to be updated. This can be done with `bin/upgrade combine_bundles -S`
- The `last_compilation` timestamp of the bundle doesn't need to be updated as it's used only in development mode as a http cache key. Just disable the cache in the browser or hit hard reload.
- If there's no css, simply omit the css steps.

### CODE REVIEW

**Comment by djowett-ftw** [comment]
Can I add that we should be:

a) Using a [requirejs](https://docs.plone.org/adapt-and-extend/theming/resourceregistry.html#updating-non-amd-scripts) or [UMD pattern](https://github.com/umdjs/umd/blob/master/templates/amdWeb.js) where possible

b) testing that JavaScript functions in production mode (that means setting `debug-mode off` in `zope.conf` (or buildout.cfg) and running with `bin/instance console`

**Comment by djowett-ftw** [comment]
Also I recommend adding these lines to `build.js`

    generateSourceMaps: true,
    // Uncomment the line below for JS development
    // optimize: "none",

**Comment by jone** [comment]
@buchi is this finished?

**Comment by buchi** [comment]
Added upgrade step.
This should be ready now.

**Comment by tinagerber** [comment]
Changelog entry is missing.

**Comment by Nachtalb** [comment]
@buchi I added the discussed changes.

**Pull request merged**
