### PR TITLE
No longer apply IDexterityTranslatable behavior automatically.

### PR DESCRIPTION
**Pull request by maethu**
- First zcml:condition only works in zcml files, not in xml.
- Second the behavior should be applied by a policy, not by default.
  Only a few will have plone.app.multilingual installed.

### CODE REVIEW

**Comment by mbaechtold** [comment]
@maethu, could you please rebase?

**Comment by jone** [comment]
@maethu updates?

**Comment by jone** [comment]
@maethu ❔

**Comment by mbaechtold** [comment]
@maethu, was ist der Grund für die Schliessung diese PR?

**Pull request closed without merging**
